# Generated by Django 2.1.7 on 2019-02-26 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_exist_child_folder', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('file_type_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('file_type_name', models.CharField(max_length=500)),
                ('file_type_describe', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.FileType'),
        ),
    ]
