# Generated by Django 2.1.7 on 2019-02-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='MyFiles',
        ),
        migrations.AlterField(
            model_name='filetype',
            name='file_type_describe',
            field=models.CharField(max_length=2000, verbose_name='文件类别描述'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='file_type_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='文件类别编码'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='file_type_name',
            field=models.CharField(max_length=500, verbose_name='文件类别名称'),
        ),
    ]
