# Generated by Django 2.1.7 on 2019-02-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_auto_20190227_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetype',
            name='file_folder_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
